# Generated by Django 5.2 on 2025-04-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Department Head', 'Department Head'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('Designer', 'Designer')], max_length=30),
        ),
    ]
