# Generated by Django 5.2 on 2025-04-10 10:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour for billing purposes', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
