# Generated by Django 5.2 on 2025-04-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_timesheet_status_timesheet_subtask_timesheet_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
