# Generated by Django 5.2 on 2025-04-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_timesheet_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_entries', to='core.resource'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='reviewed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
