# Generated by Django 5.2 on 2025-04-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_role_alter_resource_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='role',
            field=models.CharField(choices=[('Project Lead', 'Project Lead'), ('Department Head', 'Department Head'), ('Delivery Lead', 'Delivery Lead'), ('Software Engineer', 'Software Engineer'), ('Software Engineer Trainee', 'Software Engineer Trainee')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
