# Generated by Django 5.2 on 2025-04-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_resource_role_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('access_level', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='role',
            field=models.CharField(choices=[('Project Lead', 'Project Lead'), ('Department Head', 'Department Head'), ('Delivery Lead', 'Delivery Lead'), ('Lead UI/UX Developer', 'Lead UI/UX Developer'), ('Software Engineer Trainee', 'Software Engineer Trainee'), ('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Intern - Software Engineer', 'Intern - Software Engineer'), ('Senior Automation Engineer', 'Senior Automation Engineer'), ('Data Analyst', 'Data Analyst'), ('Automation Engineer', 'Automation Engineer'), ('System Analyst', 'System Analyst'), ('Junior Automation Engineer', 'Junior Automation Engineer'), ('ESG Data Analyst Intern', 'ESG Data Analyst Intern')], max_length=30),
        ),
    ]
