# Generated by Django 5.2 on 2025-04-30 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_resource_role_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttaskassignment',
            name='task_status',
            field=models.CharField(choices=[('Yet to Start', 'Yet to Start'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Completed', 'Completed')], default='Yet to Start', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='delivery_head',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__access_level': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resource'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__access_level': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_projects', to='core.resource'),
        ),
    ]
