# Generated by Django 5.2 on 2025-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUtilizationMV',
            fields=[
                ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=255)),
                ('commercial', models.CharField(max_length=50)),
                ('hours_worked', models.FloatField()),
                ('cost_spent', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('is_leave_day', models.BooleanField()),
                ('is_working_day', models.BooleanField()),
            ],
            options={
                'db_table': 'employee_utilization_mv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectReportMV',
            fields=[
                ('project_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('project_status', models.CharField(max_length=50)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allotted_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('worked_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_budget_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_time_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_resources_assigned', models.IntegerField()),
                ('project_lead_name', models.CharField(max_length=255)),
                ('delivery_head_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'project_report1_mv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskTracking',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('task_name', models.CharField(max_length=50)),
                ('task_status', models.CharField(max_length=50)),
                ('worked_hours', models.FloatField()),
                ('allotted_hours', models.FloatField()),
                ('remaining_hours', models.FloatField()),
                ('cost_spent', models.FloatField()),
            ],
            options={
                'db_table': 'project_task_tracking_mv',
                'managed': False,
            },
        ),
    ]
